### ISSUE TITLE
Doesn't connect to localhost server

### ISSUE THREAD

**Issue by Kaden14** [OpenBazaar/OpenBazaar-Installer#43]
I installed version 1.1.7 on Windows 10 and it booted up but wont connect to local server...  consisting problem from 1.1.6

**Comment by hoffmabc** [comment]
Can you show us here what you get if you click the Tent icon in the task bar and choose View Python Error Log?

**Comment by Kaden14** [comment]
Sure... just give me a minute...

**Comment by Kaden14** [comment]
![problem](https://cloud.githubusercontent.com/assets/7027695/16457897/cc1d7b88-3de2-11e6-8251-d34c9425d374.png)

**Comment by Kaden14** [comment]
![name that shows up](https://cloud.githubusercontent.com/assets/7027695/16457925/e7c7d810-3de2-11e6-9f2f-8ab9d3125b3a.png)

This is the name that shows up when I right click the tent in taskbar
I cant find the Python Error Log though....

**Comment by Kaden14** [comment]
Where can I find this Python Error Log???

**Comment by hoffmabc** [comment]
![image](https://cloud.githubusercontent.com/assets/45482/16461638/86c34612-3dfb-11e6-84c5-53bad6e3a31a.png)

**Comment by Kaden14** [comment]
![pythonerrorlog](https://cloud.githubusercontent.com/assets/7027695/16461844/2a0fd388-3df4-11e6-9d42-39a818950dba.png)

**Comment by Kaden14** [comment]
I see you are also on steam, lol.

**Comment by hoffmabc** [comment]
From the command line go to:
%APPDATALOCAL%\OpenBazaar\app-1.1.7\resources\OpenBazaar-Server

and run openbazaard.exe

What do you get when you do that?

**Comment by Kaden14** [comment]
![thishappens](https://cloud.githubusercontent.com/assets/7027695/16462028/09f6176e-3df5-11e6-8e77-0ae92f3fd9c8.png)

I had to screenshot very fast because it lasts for about 1 second then disappears... i managed to get a clear shot of the command prompt window and then I just cropped it.. again, it was fast..

**Comment by hoffmabc** [comment]
When you start the app will it load if you just hit retry? Do you see openbazaard.exe running in your Task Manager?

**Comment by Kaden14** [comment]
![connecting](https://cloud.githubusercontent.com/assets/7027695/16462179/b5c044ac-3df5-11e6-804b-2e1b29830c07.png)

**Comment by hoffmabc** [comment]
and then it just never goes past that?

**Comment by Kaden14** [comment]
it shows this ->
![then this](https://cloud.githubusercontent.com/assets/7027695/16462217/d6979d06-3df5-11e6-8efc-3973d3e67088.png)

**Comment by Kaden14** [comment]
![then this](https://cloud.githubusercontent.com/assets/7027695/16462236/ee6ff130-3df5-11e6-9aa9-8f82c4ca4179.png)
This is my taskbar... I have pinned the app to my taskbar and it just opens in that same tab..

**Comment by Kaden14** [comment]
Note: it only says 'connecting' for a few seconds..

**Comment by Kaden14** [comment]
Oh, and it is not openbazaar.exe - it is Electron ->
![not an exe](https://cloud.githubusercontent.com/assets/7027695/16462365/8a4b8a56-3df6-11e6-929d-ecc23e6d5e8f.png)

**Comment by hoffmabc** [comment]
close out OpenBazaar and run OpenBazaar.exe in %APPDATALOCAL%\OpenBazaar\app-1.1.7\

does it still say Electron?

**Comment by Kaden14** [comment]
![running this file](https://cloud.githubusercontent.com/assets/7027695/16462420/d8221952-3df6-11e6-8404-05147e34798b.png)
I am going to run it...

**Comment by Kaden14** [comment]
it just popped up the command prompt page..
nothing happened.

**Comment by Kaden14** [comment]
I uninstalled it and reinstalled it and it now says OpenBazaar in the taskbar.

**Comment by Kaden14** [comment]
but still no connection

**Comment by Kaden14** [comment]
When will this issue with openbazaar be fixed? It seems as if a lot of people are having trouble

**Comment by AndreyAtGitHub** [comment]
I also have such issue..

> From the command line go to:
> %APPDATALOCAL%\OpenBazaar\app-1.1.7\resources\OpenBazaar-Server
> 
> and run openbazaard.exe
> 
> What do you get when you do that?

`C:\Users\Андрей\AppData\Local\OpenBazaar\app-1.1.7\resources\OpenBazaar-Server>openbazaard.exe start
________             [94m         __________[0m
_____  \ ______   ____   ____[94m______   _____  _____________  _____ _______[0m
 /   |   \____ _/ __ \ /    \[94m|    |  _/__  \ ___   /__  \ __  \_  __ \ [0m
/    |    \  |_> >  ___/|   |  \    [94m|   \ / __ _/    /  / __ _/ __ |  | \/[0m
_______  /   **/ _**  >**_|  /[94m___**_  /(____  /_____ (____  (____  /**|[0m
        \/|**|        \/     \/  [94m     \/      \/      \/     \/     \/[0m

OpenBazaar Server v0.2.1 starting...
Traceback (most recent call last):
  File "<string>", line 308, in <module>
  File "<string>", line 232, in **init**
  File "<string>", line 270, in start
  File "<string>", line 180, in run
  File "db\datastore.py", line 44, in **init**
  File "db\datastore.py", line 57, in _initialize_database
  File "db\datastore.py", line 118, in _create_database
sqlite3.OperationalError: unable to open database file
openbazaard returned -1

C:\Users\Андрей\AppData\Local\OpenBazaar\app-1.1.7\resources\OpenBazaar-Server>`

I have the latest OpenBazaar-1.1.7_Setup_x64.exe and Windows 10

**Comment by Kaden14** [comment]
Okay. So, this is what i did and it worked; however, you might have a different issue, but it is worth the work.

Uninstall OpenBazaar - 

then go to:
file explorer > view (it should be on the top by home, share, etc] > select 'show hidden files'; then go to :
C:/users/[your user]/appData/local
find open bazaar folder and delete it.
Then reinstall. 

This should work, at least it did with me.

**Comment by Kaden14** [comment]
You might also want to go to to:
C:/users/[your user]/appData/roaming 
and delete OB folder there.

**Comment by AndreyAtGitHub** [comment]
Thank you Kaden14!
But nothing help. Possibly because of Russian characters in the path. Reinstalling several times. Also tried to install with Administrator  rights - this was even worse.

**Comment by AndreyAtGitHub** [comment]
Hi folks,
There are new errors in new version 1.1.10. And sever does not connect anyway.
`C:\Users\Андрей>C:\Users\Андрей\AppData\Local\OpenBazaar\app-1.1.10\resources\OpenBazaar-Server\openbazaard.exe
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "c:\users\brian\appdata\local\temp\pip-build-nvw4ux\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "api\ws.py", line 16, in <module>
  File "c:\users\brian\appdata\local\temp\pip-build-nvw4ux\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "config.py", line 23, in <module>
IndexError: list index out of range
openbazaard returned -1

C:\Users\Андрей>`

**Comment by comodoro** [comment]
I can confirm that I have this issue (Connection failed to default) after installation on Win 10 x64 Pro. My username (in the OS) also has a non-ASCII character in it. Deleting AppData dirs and reinstalling did not (obviously) work. Openbazaard start output:

OpenBazaar Server 0.2.5 starting...
Traceback (most recent call last):
  File "openbazaard.py", line 320, in <module>
  File "openbazaard.py", line 243, in __init__
  File "openbazaard.py", line 282, in start
  File "openbazaard.py", line 186, in run
  File "db\datastore.py", line 44, in __init__
  File "db\datastore.py", line 57, in _initialize_database
  File "db\datastore.py", line 118, in _create_database
sqlite3.OperationalError: unable to open database file
Failed to execute script openbazaard

Is it supposed to work with non-ASCII usernames? What else can I try (I would prefer not to dig into the source right now)?

OpenBazaar 1.11

**Comment by jjeffryes** [comment]
In OB 1.1.11, you shouldn't need a username or password for the local server at all. Are you using the default connection, @comodoro ? 

Try commenting out the username and password in the config file for your local server.

**Comment by comodoro** [comment]
Are we talking about the same issue? Because I do not think this is related to OpenBazaar credentials. The server does not start at all, see above. My question is what can be the cause and if it could be related to the fact that I have a non-ASCII character in my Windows username (and therefore AppData path).

**Comment by jjeffryes** [comment]
@comodoro my fault, I didn't read closely enough. 

It's possible a non-ASCII character would cause an error in the path the script uses. Can you try installing it on a new user account that doesn't have non-ASCII characters in the name?

**Comment by comodoro** [comment]
All right, that's what I was trying to avoid by asking, but sometimes one actually has to do something:) I will try tomorrow.

**Comment by comodoro** [comment]
I have just tried and can confirm that with simple ASCII username it works and openbazaard starts on the same computer with the same settings. This seems like a bug (quite common one, judging from my search), you cannot expect all Windows users to have ASCII usernames.

On the side note, I was aware there might be problems in the future when I learned that my user folder name contains diacritics, but it did not manifest itself until now.
